### ISSUE TITLE
在使用recyclerview上使用会导致上拉加载刷新回到顶部

### ISSUE THREAD

**Issue by Raysy** [ethanhua/Skeleton#1]

**Comment by ethanhua** [comment]
已修复

**Comment by liuqiangdd** [comment]
遇到了同样的问题，1.1.2版本。recyclerview 上拉加载更多的时候，列表回到了顶部。

**Comment by ethanhua** [comment]
@liuqiangdd  你是不是在 加载更多的回调动作中 调用了 skeleton.hide方法？

**Comment by liuqiangdd** [comment]
> @liuqiangdd 你是不是在 加载更多的回调动作中 调用了 skeleton.hide方法？

是的，hide方法应该在什么地方使用呢？

**Comment by ethanhua** [comment]
hide在你第一次数据返回时调用即可，保证只调用一次， 内部会每次重置adapter导致列表回到顶部
