### ISSUE TITLE
Shimmer animation

### ISSUE THREAD

**Issue by sweety000** [ethanhua/Skeleton#10]
when i apply it for view which is an item of recyclerview, when i scrolled down sometimes not getting shimmer animation for that skeleton view

**Comment by ethanhua** [comment]
@sweety000 can you provide more code context?

**Comment by ethanhua** [comment]
@sweety000 can you provide more code context?

**Comment by ethanhua** [comment]
@sweety000 Thanks for your issue and Check out the new 1.1.0 version for your need

**Comment by sweety000** [comment]
i applied skeleton and shimmer animation for recyclerview last item.(my idea is every 10 item we hit the service to get the next 10 items)in that case we use that shimmer animation to last item.when i dirctly scroled to last item .i am not getting shimmer animation again i scrolled down the onGlobalLayout method was invoked and got shimmer animation.How can i fix this issue

**Comment by sweety000** [comment]
leadListItem = viewHolder.leadListItemLL;
                            skeletonScreen = Skeleton.bind(leadListItem)
                                    .angle(30)
                                    .shimmer(true)
                                    .color(R.color.shimmerColor)
                                    .duration(1800)
                                    .load(R.layout.lead_list_item_skeleton)
                                    .show();


this is your library logic for animation:

public void startShimmerAnimation() {
        if (isAnimationStarted) {
            return;
        }

        if (getWidth() == 0) {
            startAnimationGlobalLayoutListener = new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    removeGlobalLayoutListener(this);
                    startShimmerAnimation();
                }
            };

            getViewTreeObserver().addOnGlobalLayoutListener(startAnimationGlobalLayoutListener);

            return;
        }

        Animator animator = getShimmerAnimation();
        animator.start();
        isAnimationStarted = true;
    }
here i am getting getWidth resullt 0.thats why the animation will not start.
how can i overcome this.

**Comment by sweety000** [comment]
programetically we can set shimmer(true),duration,angle. why can't you add autostart. i want to set  autostart dynamically. bcz you set autostart to false by default

**Comment by sweety000** [comment]
yeah thank you so much.
