### ISSUE TITLE
Crash possibly caused by Skeleton's ViewReplacer

### ISSUE THREAD

**Issue by minas90** [ethanhua/Skeleton#14]
Hi,
We pushed an update to our app 2 days ago, the main change being the addition of Skeleton. It is really amazing and easy to setup, for which thanks a lot!

The only issue is that we got a new crash caught by Crashlytics, which already happened few dozen times ( we have 100k active users, around 50% updated ).
After hours spent on investigation we suspect that it's caused by ViewReplacer, either by replace() or restore() when they call removeView. Earlier versions of Android (  < 7.0 ) have a bug in ViewGroup's dispatchDraw(), which crashes app mostly when you use removeView and the removed child is null during that specific moment I guess.
[Related thread on SO](https://stackoverflow.com/questions/5569267/nullpointerexception-that-doesnt-point-to-any-line-in-my-code)

And here is the relevant part of the crash log:
```
Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3330)
android.view.View.updateDisplayListIfDirty (View.java:14415)
android.view.View.getDisplayList (View.java:14452)
android.view.View.draw (View.java:15257)
android.view.ViewGroup.drawChild (ViewGroup.java:3540)
....
```

**Comment by ethanhua** [comment]
@minas90 when and where you call skeleton‘s show and hide method，can you provide more context details? according to your error log this more likely happened when perform draw view and  remove view simultaneously。

**Comment by minas90** [comment]
@ethanhua I have the following code inside feed fragment's onViewCreated:
```
        mSkeletonScreen = Skeleton.bind(mRecyclerView)
                .count(3)
                .adapter(mAdapter)
                .load(R.layout.item_skeleton)
                .show();
```

And later when feed items are loaded and I get callback, I call  mSkeletonScreen.hide();

Sadly there is no more useful details in the crash log, it's just going up the tree of my layout hierarchy.

```
android.support.design.widget.CoordinatorLayout.drawChild
...... 
android.support.v4.widget.DrawerLayout.drawChild
......
```

To be precise, it's happening ~5 times per day, but it's the only crash we have at the moment and we want to reach 0 threshold.

It's happening not because of directly Skeleton or my code, but it's a bug in Android framework. The only thing we can do is to mitigate it by tweaking the part of our code that causes the crash.

And I think I found the exact cause. Draw happens periodically when Skeleton is shimmering and my guess is that during that particular invalidation moment when ViewReplacer calls removeView for shimmerLayout and it's still animating, it causes a crash.

You call shimmerLayout.stopShimmerAnimation(); in onViewDetachedFromWindow inside ViewSkeletonScreen.generateShimmerContainerLayout(). It's a very smart code to be honest, but I'm afraid it's responsible for the crash. I guess onViewDetachedFromWindow is an async call and it's too late for stopping animation. Instead .stopShimmerAnimation(); should be called right before removeView. Otherwise even if it takes a millisecond, because of animation it may get few invalidation calls, which causes the issue.

P.S. Android has a very sophisticated rendering engine and invalidation / draw is happening every time when something on screen is changed. So why if you take a look, almost all the crashes reported by others happened because of an animation.
If you have time and interested, you can watch https://www.youtube.com/watch?v=zdQRIYOST64
to understand how exactly rendering works. I didn't know most of the details, before watching this video. :)

**Comment by minas90** [comment]
Ok, after I copied library code and took a closer look, it seems like ViewReplacer is not used for recyclerview at all, but the strange thing is that stopShimmerAnimation() is not called at all in case of recyclerview.

```
    @Override
    public void hide() {
        mRecyclerView.setAdapter(mActualAdapter);
        if (!mRecyclerView.isComputingLayout()) {
            mRecyclerView.setLayoutFrozen(false);
        }
    }
```
Before doing this you should call stopShimmerAnimation(), otherwise you may encounter strange issues.
When you set a new adapter, it not necessarily destroys persisted shimmer viewholder from previous adapter. Also setAdapter is calling setLayoutFrozen(false); by itself, no need to call it again.

**Comment by ethanhua** [comment]
thanks a lot for your advice，set a new adapter will call removeAndRecycleViews when only one adapter exist. and ShimmerLayout will stop animation when detach  from window， so i think it's not a real reason for this problem，can you show me your UI xml？ and  is there other  animation in your activity/fragment?

**Comment by minas90** [comment]
@ethanhua thanks for details! I didn't investigate shimmer layout in details and didn't know that it's calling resetShimmering() inside onDetachedFromWindow(). But it's my point, you see onDetachedFromWindow() is too late for stopping animation. You shouldn't rely on that, animation should be stopped before the view is removed. ( same for ViewReplacer ). Otherwise not always, but sometimes when it's still animating in that particular moment and it's removed, 
android.view.ViewGroup.dispatchDraw will cause null pointer exception, because of an android bug, which is trying to access mViewFlags of a null view. It's also possible to happen without any animation, but animation causes frequent invalidation and draw calls, so it increases the possibility of crashing.
Anyway I copied library code and will try to fix it myself. If I succeed, I will let you know after few days.

I have very lean UI xml for that screen and it worked without issues until now.
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.SwipeRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/swipe_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:descendantFocusability="beforeDescendants" />
</android.support.v4.widget.SwipeRefreshLayout>
```

**Comment by minas90** [comment]
Ok, so I just cache shimmer views inside onBindViewHolder

```
private List<ShimmerLayout> mShimmerLayouts = new ArrayList<>();
....
ShimmerLayout layout = (ShimmerLayout) holder.itemView;
mShimmerLayouts.add(layout);

public void stopShimmerAnimation() {
    for (ShimmerLayout shimmerLayout : mShimmerLayouts) {
        if (shimmerLayout != null) shimmerLayout.stopShimmerAnimation();
    }
    mShimmerLayouts.clear();
    mShimmerLayouts = null;
}
```

and inside hide() method before setting adapter I call mSkeletonAdapter.stopShimmerAnimation();

Of course it's not a good practice to cache recyclerview items, but as it's setting mRecyclerView.setLayoutFrozen(true); it's not an issue.
Will push an update to my app in few hours and let you know after few days if I still get the crash.
You are free to merge or not to merge these changes! :)

**Comment by minas90** [comment]
Ok, seems it resolved the issue ( didn't get any crash from new version during 2 days ), but it's a hacky code, so I'm not sure if it's a good idea to merge it into library.
Thanks a lot for your library! :)
I modified it for my needs and it was a good starting point.
