### ISSUE TITLE
Shimmering showing on CardView

### ISSUE THREAD

**Issue by myatmins** [ethanhua/Skeleton#17]
I use a CardView as root layout and shimmering is showing on the whole view. Already tried setting transparent background. Didn't work.

**Comment by fxsankdang** [comment]
yes, me too。And I replace item_skeleton_xx.xml's root xml to Relativelayout,but still dosen't work

**Comment by myatmins** [comment]
I got it. Use `app:cardBackgroundColor="@android:color/transparent"`

**Comment by fxsankdang** [comment]
OK，I will try.thank you,bro.
