### ISSUE TITLE
Skeleton recyclerview

### ISSUE THREAD

**Issue by alahammad** [ethanhua/Skeleton#18]
Hello,

Thanks for your library it's very handful, i have issue when implement it using the following code : 
Skeleton.bind(recyclerview)
                .adapter(adapter)
                .shimmer(true)
                .angle(20)
                .frozen(true)
                .duration(1200)
                .count(10)
                .load(R.layout.account_skeleton_row)
                .show()

the row in recyclerview doesn't full the screen width, can check this issue.

Thanks,

**Comment by ajayqualwebs** [comment]
Width depends on your layout width please check once, because I am using the same library and It's working properly.

**Comment by alahammad** [comment]
@ajayqualwebs in your sample code try to modify RecyclerViewActivity to this : 
 
PersonAdapter adapter = new PersonAdapter();
            final SkeletonScreen skeletonScreen = Skeleton.bind(recyclerView)
                    .adapter(adapter)
                    **.load(R.layout.item_skeleton_person)
                    .shimmer(true)**
                    .show();


then you will notice the issue

**Comment by frankenten13** [comment]
Same issue, and add this View to layout to fix
```
    <View
        android:layout_width="0dp"
        android:layout_height="1px"
        android:background="#dfdfdf"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintLeft_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Comment by ethanhua** [comment]
make sure the item skeleton layout width is match_parent
