### ISSUE TITLE
Issue in Recyclerview with horizontal layout

### ISSUE THREAD

**Issue by winphyoethu** [ethanhua/Skeleton#23]
it is not showing skeleton item full width in Recyclerview with horizontal layout. it is working perfectly in vertical layout.

**Comment by dyguests** [comment]
Same Problem.

![79744d934257d52bd89c235a75d59ab3](https://user-images.githubusercontent.com/7933189/49575764-75a8ea80-f97e-11e8-86ca-878713a36b4e.jpg)
![42ae2a0c5796074cb0ce32cfceed9667](https://user-images.githubusercontent.com/7933189/49575770-780b4480-f97e-11e8-91f3-af56b2cdd5cc.jpg)

**Comment by ethanhua** [comment]
@winphyoethu @dyguests you should make sure the item skeleton layout width is match_parent

**Comment by dyguests** [comment]
@ethanhua Yes.

Show this:
![2018-12-10 4 33 27](https://user-images.githubusercontent.com/7933189/49719887-646f1f00-fc99-11e8-89b8-f3d672236259.png)

https://github.com/dyguests/LinRefreshLayout/blob/master/sample/src/main/java/com/fanhl/linrefreshlayout/sample/DrawstringActivity.kt#L54

https://github.com/dyguests/LinRefreshLayout/blob/master/sample/src/main/res/layout/item_view.xml#L6

**Comment by ethanhua** [comment]
@dyguests not your actual item_view holder but your skeleton_item_view .  see sample/ RecyclerViewActivity、NewsAdapter

**Comment by ethanhua** [comment]
@dyguests  thanks for your issue .  please check the new version 1.1.2 for your need

**Comment by dyguests** [comment]
![745fe79d220b75cdea2e39f39886e310](https://user-images.githubusercontent.com/7933189/49782512-9643bc80-fd51-11e8-8610-4ae105df7e0b.jpg)
![20283fe54ef02cfa633e83f0df6e64a1](https://user-images.githubusercontent.com/7933189/49782513-9643bc80-fd51-11e8-9778-aab5ba3dc11c.jpg)

It's match parent(thx!),
 but all item element in itemView is hided.

Use Skeleton:

	        skeletonScreen = Skeleton.bind(recycler_view)
	            .adapter(adapter)
	            .load(R.layout.item_view)
	            .show()

Adapter:

		class DefaultAdapter : BaseQuickAdapter<Int, BaseViewHolder>(R.layout.item_view) {
		    @SuppressLint("SetTextI18n")
		    override fun convert(helper: BaseViewHolder?, item: Int?) {
		        helper?.itemView?.apply {
		            img_cover.imageResource = R.mipmap.ic_launcher
		            tv_title.text = "Title$item"
		            tv_content.text = "Content$item ${System.currentTimeMillis()}"
		        }
		    }
		}
