### ISSUE TITLE
min sdk

### ISSUE THREAD

**Issue by ClaudeHangui** [ethanhua/Skeleton#3]
One word: NICE !!
But why is the min SDK set to 15 ??
From what I see the library looks compatible for devices lower than that yes ?

**Comment by ethanhua** [comment]
@ClaudeHangui  my AS create project the default setting min SDK is 15.  also  Most devices are above 15 now.  you can fork it  to change the min SDK to lower for your need. later i will update it

**Comment by ClaudeHangui** [comment]
ok will do !!
