### ISSUE TITLE
fragment+view Pager don't work

### ISSUE THREAD

**Issue by chengtaowan** [ethanhua/Skeleton#30]
Hello , How to work in Fragment+ViewPager.

**Comment by ethanhua** [comment]
in this case： Do not use fragment's RootView as the parameter value of the bind function and call it in onViewCreated function or later @chengtaowan

**Comment by chengtaowan** [comment]
Thank you! Big brother.

**Comment by raghavsatyadev** [comment]
@chengtaowan can you provide your code of layout and skeleton? I am stuck at the same issue. Already tried above suggestions but skeleton is only showing animations on Tab View above View pager and not in View Pager

**Comment by RafaRuiz** [comment]
But, what about if your Fragment is a partial layout that has to load and you want to Shimmer everything?
