### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ClaudeHangui** [ethanhua/Skeleton#4]
I'm using the Shimmerlayout in a viewpager....Each fragment of the viewpager has a recyclerview...
So upon scrollling inside one of my fragments, my app crashed and I get this error:

    at android.graphics.Bitmap.nativeCreate(Native Method)                                                                                    
    at android.graphics.Bitmap.createBitmap                                                                                        
 
Here is the method in question:
         `private Bitmap createBitmap(int width, int height) {
            try {
                  return Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            } catch (OutOfMemoryError e) {
                System.gc();
                return Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            }
         #}`

**Comment by ethanhua** [comment]
@ClaudeHangui can you provide more details ? generally, it's because you load  larger bitmap , so check the memory usage of your application.

**Comment by jeancsanchez** [comment]
The same thing happened to me. In my case, my layout had a default background image where I  used to test. I just removed it and it worked.

**Comment by ClaudeHangui** [comment]
@ethanhua   It's a default image which serves as a placeholder....When you mean I may be loading a larger bitmap, is there a recommended size for the bitmap ??

**Comment by ethanhua** [comment]
@ClaudeHangui @jeancsanchez How many times the crash occured ? and what kind of phone the crash happened? and you can see this[https://github.com/team-supercharge/ShimmerLayout/issues/25](url)

**Comment by ethanhua** [comment]
@ClaudeHangui @jeancsanchez How many times the crash occured ? and what kind of phone the crash happened? also you can see this:
  https://github.com/team-supercharge/ShimmerLayout/issues/25
