### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by aLittleGreens** [ethanhua/Skeleton#47]
Attempt to invoke virtual method 'void android.graphics.Matrix.set(android.graphics.Matrix)' on a null object reference
1 android.graphics.Shader.copyLocalMatrix(Shader.java:159)
--
2 android.graphics.LinearGradient.copy(LinearGradient.java:129)
3 android.graphics.ComposeShader.copy(ComposeShader.java:96)
4 android.graphics.Shader.mzReversalCopy(Shader.java:134)
5 com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:830)
6 com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:810)
7 android.view.RecordingCanvas.drawRect(RecordingCanvas.java:622)
8 io.supercharge.shimmerlayout.ShimmerLayout.drawShimmer(ShimmerLayout.java:261)
9 io.supercharge.shimmerlayout.ShimmerLayout.dispatchDrawShimmer(ShimmerLayout.java:250)
10 io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:106)
11 android.view.View.draw(View.java:19355)
12 android.view.View.updateDisplayListIfDirty(View.java:18295)
13 android.view.View.draw(View.java:19073)
14 android.view.ViewGroup.drawChild(ViewGroup.java:4236)
15 androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:4820)

**Comment by lxt-sky** [comment]
同上，我也报了这个问题

**Comment by aLittleGreens** [comment]
这个只能下载源代码，去捕获异常

**Comment by LvZhenDong** [comment]
有没有人解决了这个问题的

**Comment by xinshengze** [comment]
这个问题解决了吗

**Comment by wenqian-cai-tuya** [comment]
Thanks for your message

**Comment by MarkRaoAndroid** [comment]
> 这个只能下载源代码，去捕获异常

不好意思，没太明白，下载源代码捕获异常是指下载魅族的源代码吗？谢谢

**Comment by wenqian-cai-tuya** [comment]
Thanks for your message
