### ISSUE TITLE
Loading skeleton return after data arrived

### ISSUE THREAD

**Issue by edenhalfon** [ethanhua/Skeleton#5]
Im using the skeleton and when I'm binding it to the recycler view it's automatically disappear when data is in place, but when I enter to another fragment and then return to the one with the loading the skeleton returns again.
I tried to use the hide() function but it just hiding the recycler as well.

**Comment by ethanhua** [comment]
@edenhalfon can you provide your code？and make sure not call RecyclerView setAdapter method after call Skeleton's show method

**Comment by Radhakrishn** [comment]
I'm getting exception when i try to load same screen again, first time it is working, 3rd or 4th time its crashing. " java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference"
