### ISSUE TITLE
Crash 'boolean android.graphics.Bitmap.isRecycled()"

### ISSUE THREAD

**Issue by Radhakrishn** [ethanhua/Skeleton#6]
I'm getting exception when i try to load same screen again, first time it is working, 3rd or 4th time its crashing. " java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference"

**Comment by ethanhua** [comment]
@Radhakrishn  can you provide more information about excepition StackTrace and the code of  using skeleton?
