### ISSUE TITLE
Failed to resolve: com.ethanhua:skeleton:1.1.2

### ISSUE THREAD

**Issue by RYANFRANKLIN237** [ethanhua/Skeleton#62]
I have this dependency :
 implementation 'com.ethanhua:skeleton:1.1.2'
 
 in my build.gradle  java anroid studio project , and i can't download the dependency anymore ? does  anyone have a work around for this issue???

**Comment by w201** [comment]
JCenter closed, and lib is deprecated... so probably the answer is yes this is the end...

**Comment by iCodeDesigns** [comment]
Same issue! any one got resolved?

**Comment by RYANFRANKLIN237** [comment]
use a different library for shimmers if that's what you want to do with this dependency, you can use this library for shimmers:
implementation 'com.facebook.shimmer:shimmer:0.5.0'
that's what i did
