### ISSUE TITLE
Can't find any way to have this to work on a RecyclerView that is Horizontal.

### ISSUE THREAD

**Issue by TheRealNox** [ethanhua/Skeleton#7]
I've got such code before using your framework:
`
mRecyclerView.setLayoutManager(new LinearLayoutManager(rootView.getContext(), LinearLayoutManager.HORIZONTAL, false));
`
But if I use your framework, even when specifying count I still can see only one item, but I guess it's only because it's in Vertical mode.

**Comment by ethanhua** [comment]
if your recyclerView item width is equals to screen width then just show one item because in Skeleton show method will  call RecyclerView.setLayoutFrozen(true)，I will consider whether to open this configuration in later version

**Comment by TheRealNox** [comment]
@ethanhua Thank you for clarifying. That's pretty much what I thought.
If I can be of any help, let me know :).

**Comment by TheRealNox** [comment]
we could have:
`
public Builder isHorizontal(Boolean isHorizontal) {
    this.mIsHoriozontal = isHorizontal;
    return this;
}
`
and then:
`
    public void show() {
        mRecyclerView.setAdapter(mSkeletonAdapter);
        if (!mRecyclerView.isComputingLayout() && mIsHorizontal) {
            mRecyclerView.setLayoutFrozen(true);
        }
    }
`

**Comment by ethanhua** [comment]
@TheRealNox  the latest version 1.0.1 has been released.

**Comment by TheRealNox** [comment]
Just saw that.
It's working a bit better but still not perfect, here is what I get sing frozen == false:
![screenshot_1516660515](https://user-images.githubusercontent.com/1244091/35248078-a3560de2-0031-11e8-9d13-cf92e1b5d69c.png)
![screenshot_1516660522](https://user-images.githubusercontent.com/1244091/35248081-a741d198-0031-11e8-92cb-e7b13c3d6a3b.png)
So as you can see, the space between the two items is way too big, looks like it's trying to fill the width before drawing another items.
Any idea?

**Comment by TheRealNox** [comment]
It seems like you're not creating an horizontal LayoutManager

**Comment by ethanhua** [comment]
@TheRealNox  the space between the items depend on your skeleton layout and your RecyclerView ItemDecoration, Skeleton will not change them, so adjust them for your needs

**Comment by TheRealNox** [comment]
Well, if I remove your skeleton, it's all working perfectly fine and as expected...
I'll try to see what's going on.
